Traceback (most recent call last):
  File "/gpfsnyu/home/km3888/oyster/launch_experiment.py", line 141, in <module>
    main()
  File "/gpfsnyu/home/km3888/.conda/envs/rl/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/gpfsnyu/home/km3888/.conda/envs/rl/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/gpfsnyu/home/km3888/.conda/envs/rl/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfsnyu/home/km3888/.conda/envs/rl/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/gpfsnyu/home/km3888/oyster/launch_experiment.py", line 133, in main
    with open(os.path.join(config)) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/cheetah-dir.json'
